<?php 
echo '{
    "status":true,
    "data":[
        {
            "imgUrl":"/img/topic/topic1.png",
            "href":"http://www.baidu.com"
        },
        {
            "imgUrl":"/img/topic/topic2.png",
            "href":"http://www.baidu.com"
        },
        {
            "imgUrl":"/img/topic/topic3.png",
            "href":"http://www.baidu.com"
        },
        {
            "imgUrl":"/img/topic/topic4.png",
            "href":"http://www.baidu.com"
        }
    ]
}';
?>